openapi: "3.0.0"
info:
  version: 1.0.0
  title: Login demo
paths:
  /user:
    get:
      summary: login system
      operationId: loginUser
      tags: 
      - user
      parameters: 
      - name: "username"
        in: "query"
        description: "user name for login"
        required: true
        schema:
          type: "string"
      - name: "password"
        in: "query"
        description: "password for login"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "login fail"
components:
  schemas:
    User:
      type: object
      required: 
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string