swagger: "2.0"
info:
  description: "This is a demo login swagger."
  version: "1.0.0"
  title: "Login"
tags:
- name: "User"
  description: "Operations about user"
schemes:
- "https"
- "http"
paths:
  /User/login:
    get:
      tags:
      - "User"
      summary: "Login in system"
      description: ""
      operationId: "userlogin"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "password for login"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "login fail"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"